server:
  port: 8888

spring:
  application:
    name: config-server


  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  cloud:
    config:
      server:
        git:
          uri: https://github.com/mandeotv1234/graduation-project-config
          clone-on-start: true
          default-label: main

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
